name: Moodle plugin CI

on:
  push:
  pull_request:

jobs:
  moodle-plugin-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        moodle-branch: ['MOODLE_500_STABLE']
        php-version: ['8.2']

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, dom, gd, intl, json, mbstring, mysqli, soap, xml, xmlrpc, zip
          coverage: none

      - name: Install Moodle Plugin CI
        run: |
          composer create-project moodlehq/moodle-plugin-ci ci ^4 --no-interaction

      - name: Install Moodle
        run: >
          ./ci/bin/moodle-plugin-ci install
          --moodle=${{ matrix.moodle-branch }}
          --plugin=$GITHUB_WORKSPACE
      - name: Run code checker
        run: |
          ./ci/bin/moodle-plugin-ci phpcs

      - name: Run PHP lint
        run: |
          ./ci/bin/moodle-plugin-ci phplint

      - name: Run mustache lint
        run: |
          ./ci/bin/moodle-plugin-ci mustache

      - name: Run PHPUnit
        run: |
          ./ci/bin/moodle-plugin-ci phpunit
